<ul class="commentar-comments">
    <?php foreach ($this->comments as $comment) { ?>
        <li id="<?php echo $comment->getId(); ?>">
            <img src="https://www.gravatar.com/avatar/<?php echo md5($comment->getUser()->getEmail()); ?>?s=32&d=identicon&r=PG&f=1" >
            <article>
                <header>
                    <ul>
                        <li class="username">
                            <a href="#"><?php echo htmlspecialchars($comment->getUser()->getUsername(), ENT_QUOTES); ?></a>
                            <?php if($comment->getUser()->isAdmin()) { ?>
                                <span class="mod" title="This post is made by a moderator">MOD</span>
                            <?php } ?>
                        </li>
                        <li class="date">
                            <a href="#<?php echo $comment->getId(); ?>"><?php echo $this->renderView('TimeAgo', ['timestamp' => $comment->getTimestamp()]); ?></a>
                        </li>
                    </ul>
                </header>
                <main>
                    <div class="icon-comments"></div>
                    <div class="triangle-topleft"></div>
                    <?php echo $this->renderView('PlainText', ['postBody' => $comment->getContent()]); ?>
                    <?php if ($comment->getUpdated() !== null) { ?>
                        <p class="editedBy">
                            Edited by <?php echo htmlspecialchars($comment->getUser()->getUsername(), ENT_QUOTES); ?>, <?php echo $this->renderView('TimeAgo', ['timestamp' => $comment->getUpdated()]); ?>
                        </p>
                    <?php } ?>
                </main>
                <footer>
                    <span class="score">
                        <?php echo $comment->getScore(); ?>
                    </span>
                    <a href="" class="thumbsUp icon-like"></a>
                    <a href="" class="thumbsDown icon-dislike"></a>
                    <span class="share icon-share">
                        Share
                        <a href="" class="icon-facebook"></a>
                        <a href="" class="icon-twitter"></a>
                        <a href="" class="icon-linkedin"></a>
                    </span>
                    <a href="/comments/<?php echo $this->postId; ?>/reply/<?php echo $comment->getId(); ?>" class="reply icon-reply">
                        Reply
                    </a>
                    <a href="" class="flag icon-flag">
                        Flag
                    </a>
                     <a href="" class="edit icon-pencil">
                        Edit
                    </a>
                     <a href="/comments/<?php echo $this->postId; ?>/delete/<?php echo $comment->getId(); ?>" class="delete icon-delete">
                        Remove
                    </a>
                </footer>
            </article>
            <?php if ($comment->hasChildren()) { ?>
                <a href="" class="button showReplies icon-plus" data-toggle="Hide">
                    <span>Show</span>
                    <?php echo count($comment->getChildren()); ?> replies
                </a>
                <?php echo $this->renderView('CommentList', ['comments' => $comment->getChildren(), 'postId' => $this->postId]); ?>
            <?php } ?>
        </li>
    <?php } ?>
</ul>
