<ul class="commentar-comments">
    <?php foreach ($data['comments'] as $comment) { ?>
        <li>
            <img src="https://www.gravatar.com/avatar/<?php echo md5($comment['user']['email']); ?>?s=32&d=identicon&r=PG&f=1" >
            <article>
                <header>
                    <ul>
                        <li class="username">
                            <a href="#">
                                <?php echo $comment['user']['username']; ?>
                            </a>
                        </li>
                        <li class="date">
                            3 minutes ago
                        </li>
                    </ul>
                </header>
                <main>
                <div class="icon-comments"></div>
                    <div class="triangle-topleft"></div>
                    <p>
                        <?php echo $comment['content']; ?>
                    </p>
                    <p class="editedBy">
                        Edited by <?php echo $comment['user']['username']; ?>, 1 minutes ago
                    </p>
                </main>
                <footer>
                    <span class="score">
                        <?php echo $comment['score']; ?>
                    </span>
                    <a href="" class="thumbsUp icon-like"></a>
                    <a href="" class="thumbsDown icon-dislike"></a>
                    <span class="share icon-share">
                        Share
                        <a href="" class="icon-facebook"></a>
                        <a href="" class="icon-twitter"></a>
                        <a href="" class="icon-linkedin"></a>
                    </span>
                    <a href="" class="reply icon-reply">
                        Reply
                    </a>
                    <a href="" class="flag icon-flag">
                        Flag
                    </a>
                     <a href="" class="edit icon-pencil">
                        Edit
                    </a>
                     <a href="" class="delete icon-delete">
                        Remove
                    </a>
                </footer>
            </article>
            <?php 
                if ($comment['children']) {
                    echo $this->loadTemplate('blocks/comments.phtml', ['comments' => $comment['children']]);
                } 
            ?>
        </li>
    <?php } ?>
</ul>