before_commands:
    - "composer install --no-dev --prefer-source"

tools:
    php_code_coverage:
        enabled: true
        test_command: phpunit -c phpunit.xml.dist
        #filter:
            #paths: ["src"]
    php_code_sniffer:
        enabled: true
        config:
            standard: PSR2
        filter:
            paths: ["src/*"]
    php_cpd:
        enabled: true
        excluded_dirs: ["test", "vendor"]
    php_cs_fixer:
        enabled: true
        config:
            level: all
        filter:
            paths: ["src/*", "test/*"]
    php_loc:
        enabled: true
    php_mess_detector:
        enabled: true
        filter:
            paths: ["src/*"]
    php_pdepend:
        enabled: true
        excluded_dirs: ["test", "vendor", "public", "themes"]
    php_analyzer: true
    php_analyzer:
        filter:
            paths: ["src/*", "test/*"]
    sensiolabs_security_checker: true
