<!DOCTYPE html>
<html>
    <head>
        <title>Commentar</title>
        <meta charset="utf-8">
        <script>'article aside footer header main nav section time'.replace(/\w+/g,function(n){document.createElement(n)})</script>
        <link href="/css/style.css" rel="stylesheet" type="text/css" media="screen">
        <link href="/css/icons.css" rel="stylesheet" type="text/css" media="screen">
        <link rel="shortcut icon" type="image/x-icon" href="/favicon.ico">
    </head>
    <body>
        <div id="commentar-container">
            <form class="commentar-post" action="/" method="post">
                <img src="https://www.gravatar.com/avatar/8f5fab301228ede0da59abbcaab5ec88?s=32&d=identicon&r=PG&f=1" >
                <div class="formTriangle-topleft"></div>
                <div class="textWrapper">
                    <textarea></textarea>
                    <input type="submit" value="Send"/>
                    <a class="button icon-upload" href="">Upload</a>
                </div>
            </form>
            <?php echo $this->content; ?>
            <p id="poweredBy">
                Powered by
                <a href="https://github.com/Commentar/Commentar" target="_blank" class="icon-commentar-logo"></a>
            </p>
        </div>
        <script src="/js/jquery-1.10.2.min.js"></script>
        <script src="/js/script.js"></script>
    </body>
</html>
