<!DOCTYPE html>
<html>
    <head>
        <title>Commentar</title>
        <meta charset="utf-8">
        <script>'article aside footer header main nav section time'.replace(/\w+/g,function(n){document.createElement(n)})</script>
        <link href="//fonts.googleapis.com/css?family=Roboto+Condensed:400,700" rel="stylesheet" type="text/css">
        <link href="/css/style.css" rel="stylesheet" type="text/css" media="screen">
        <link href="/css/icons.css" rel="stylesheet" type="text/css" media="screen">
        <script src="/js/jquery-1.10.2.min.js"></script>
        <script src="/js/script.js"></script>
        <link rel="shortcut icon" type="image/x-icon" href="/favicon.ico">
    </head>
    <body>
        <div style="width: 960px; margin: 10px auto;">
            <div class="commentar-container">
                <div class="commentar-post">
                    <img src="https://www.gravatar.com/avatar/8f5fab301228ede0da59abbcaab5ec88?s=32&d=identicon&r=PG&f=1" >
                    <div class="commentar-post-container">
                        <div class="commentar-post-field-container">
                            <textarea></textarea>
                        </div>
                    </div>
                </div>
                <ul class="commentar-comments">
                    <li>
                        <img src="https://www.gravatar.com/avatar/8f5fab301228ede0da59abbcaab5ec88?s=32&d=identicon&r=PG&f=1" >
                        <article>
                            <header>
                                <ul>
                                    <li class="username"><a href="#">PeeHaa</a></li>
                                    
                                    <li class="date">3 minutes ago</li>
                                </ul>
                            </header>
                            <main>
                            <div class="icon-commentar-icon"></div>
                                <div class="triangle-topleft"></div>
                                <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Maecenas cursus sapien sapien, vel vestibulum tortor pellentesque ac. Quisque euismod lacus sapien, sit amet placerat nulla blandit quis. Etiam lobortis dignissim lorem, commodo faucibus massa rutrum et. Fusce a auctor sem, porttitor rhoncus erat. Maecenas ligula nunc, cursus pretium elit sed, cursus condimentum mauris. Aliquam lacinia ligula malesuada velit varius, a euismod quam fermentum. Maecenas ultrices dignissim lorem, id mattis lectus rutrum rhoncus. Maecenas felis odio, ultrices sit amet odio sed, malesuada hendrerit leo. Nulla vitae metus urna. Pellentesque rhoncus dolor in lectus condimentum, ut tempor dolor facilisis. Cras et rutrum justo.</p>
                            </main>
                            <footer>
                                <span class="score">2</span>
                                <a href="" class="thumbsUp icon-like"></a>
                                <a href="" class="thumbsDown icon-dislike"></a>
                                <span class="share icon-share"> 
                                    Share: 
                                    <a href="" class="icon-facebook"></a>
                                    <a href="" class="icon-twitter"></a>
                                    <a href="" class="icon-linkedin"></a>
                                </span>
                                <a href="" class="reply icon-reply">Reply</a>
                                <a href="" class="flag icon-flag">Flag</a>
                            </footer>
                        </article>
                    </li>
                    <li>
                        <img src="https://www.gravatar.com/avatar/8f5fab301228ede0da59abbcaab5ec88?s=32&d=identicon&r=PG&f=1" >
                        <article>
                            <header>
                                <ul>
                                    <li class="username"><a href="#">PeeHaa</a></li>
                                    
                                    <li class="date">3 minutes ago</li>
                                </ul>
                            </header>
                            <main>
                            <div class="icon-commentar-icon"></div>
                                <div class="triangle-topleft"></div>
                                <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Maecenas cursus sapien sapien, vel vestibulum tortor pellentesque ac. Quisque euismod lacus sapien, sit amet placerat nulla blandit quis. Etiam lobortis dignissim lorem, commodo faucibus massa rutrum et. Fusce a auctor sem, porttitor rhoncus erat. Maecenas ligula nunc, cursus pretium elit sed, cursus condimentum mauris. Aliquam lacinia ligula malesuada velit varius, a euismod quam fermentum. Maecenas ultrices dignissim lorem, id mattis lectus rutrum rhoncus. Maecenas felis odio, ultrices sit amet odio sed, malesuada hendrerit leo. Nulla vitae metus urna. Pellentesque rhoncus dolor in lectus condimentum, ut tempor dolor facilisis. Cras et rutrum justo.</p>
                            </main>
                            <footer>
                                <span class="score">2</span>
                                <a href="" class="thumbsUp icon-like"></a>
                                <a href="" class="thumbsDown icon-dislike"></a>
                                <span class="share icon-share"> 
                                    Share: 
                                    <a href="" class="icon-facebook"></a>
                                    <a href="" class="icon-twitter"></a>
                                    <a href="" class="icon-linkedin"></a>
                                </span>
                                <a href="" class="reply icon-reply">Reply</a>
                                <a href="" class="flag icon-flag">Flag</a>
                            </footer>
                        </article>
                    </li>
                    <li>
                        <img src="https://www.gravatar.com/avatar/8f5fab301228ede0da59abbcaab5ec88?s=32&d=identicon&r=PG&f=1" >
                        <article>
                            <header>
                                <ul>
                                    <li class="username"><a href="#">PeeHaa</a></li>
                                    
                                    <li class="date">3 minutes ago</li>
                                </ul>
                            </header>
                            <main>
                            <div class="icon-commentar-icon"></div>
                                <div class="triangle-topleft"></div>
                                <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Maecenas cursus sapien sapien, vel vestibulum tortor pellentesque ac. Quisque euismod lacus sapien, sit amet placerat nulla blandit quis. Etiam lobortis dignissim lorem, commodo faucibus massa rutrum et. Fusce a auctor sem, porttitor rhoncus erat. Maecenas ligula nunc, cursus pretium elit sed, cursus condimentum mauris. Aliquam lacinia ligula malesuada velit varius, a euismod quam fermentum. Maecenas ultrices dignissim lorem, id mattis lectus rutrum rhoncus. Maecenas felis odio, ultrices sit amet odio sed, malesuada hendrerit leo. Nulla vitae metus urna. Pellentesque rhoncus dolor in lectus condimentum, ut tempor dolor facilisis. Cras et rutrum justo.</p>
                            </main>
                            <footer>
                                <span class="score">2</span>
                                <a href="" class="thumbsUp icon-like"></a>
                                <a href="" class="thumbsDown icon-dislike"></a>
                                <span class="share icon-share"> 
                                    Share: 
                                    <a href="" class="icon-facebook"></a>
                                    <a href="" class="icon-twitter"></a>
                                    <a href="" class="icon-linkedin"></a>
                                </span>
                                <a href="" class="reply icon-reply">Reply</a>
                                <a href="" class="flag icon-flag">Flag</a>
                            </footer>
                        </article>
                        <ul class="commentar-comments">
                            <li>
                                <img src="https://www.gravatar.com/avatar/8f5fab301228ede0da59abbcaab5ec88?s=32&d=identicon&r=PG&f=1" >
                                <article>
                                    <header>
                                        <ul>
                                            <li class="username"><a href="#">PeeHaa</a></li>
                                            
                                            <li class="date">3 minutes ago</li>
                                        </ul>
                                    </header>
                                    <main>
                                    <div class="icon-commentar-icon"></div>
                                <div class="triangle-topleft"></div>
                                        <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Maecenas cursus sapien sapien, vel vestibulum tortor pellentesque ac. Quisque euismod lacus sapien, sit amet placerat nulla blandit quis. Etiam lobortis dignissim lorem, commodo faucibus massa rutrum et. Fusce a auctor sem, porttitor rhoncus erat. Maecenas ligula nunc, cursus pretium elit sed, cursus condimentum mauris. Aliquam lacinia ligula malesuada velit varius, a euismod quam fermentum. Maecenas ultrices dignissim lorem, id mattis lectus rutrum rhoncus. Maecenas felis odio, ultrices sit amet odio sed, malesuada hendrerit leo. Nulla vitae metus urna. Pellentesque rhoncus dolor in lectus condimentum, ut tempor dolor facilisis. Cras et rutrum justo.</p>
                                    </main>
                                    <footer>
                                        <span class="score">2</span>
                                        <a href="" class="thumbsUp icon-like"></a>
                                        <a href="" class="thumbsDown icon-dislike"></a>
                                        <span class="share icon-share"> 
                                            Share: 
                                            <a href="" class="icon-facebook"></a>
                                            <a href="" class="icon-twitter"></a>
                                            <a href="" class="icon-linkedin"></a>
                                        </span>
                                        <a href="" class="reply icon-reply">Reply</a>
                                        <a href="" class="flag icon-flag">Flag</a>
                                    </footer>
                                </article>
                            </li>
                        </ul>
                    </li>
                </ul>
            </div>
        </div>
        <div id="poweredBy">Powered by <a href="https://github.com/Commentar/Commentar" target="_blank" class="icon-commentar-logo"></a></div>
    </body>
</html>
